# Generated by Django 4.2.6 on 2023-10-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_link', models.URLField()),
                ('model_number', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('operating_system', models.CharField(max_length=50)),
                ('camera_resolution', models.CharField(max_length=20)),
                ('battery_capacity', models.PositiveIntegerField()),
                ('storage_capacity', models.PositiveIntegerField()),
                ('RAM', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_link', models.URLField()),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.PositiveIntegerField()),
                ('storage_capacity', models.PositiveIntegerField()),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('operating_system', models.CharField(max_length=50)),
                ('graphics_card', models.CharField(max_length=50)),
                ('ports', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('buy_link', models.URLField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
