# Generated by Django 4.2.6 on 2023-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0003_article_updated_by_article_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='brand',
            field=models.TextField(default='Brand Name'),
        ),
    ]
