# Generated by Django 4.2.6 on 2023-10-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0004_pc_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='brand',
        ),
    ]
