# Generated by Django 4.2.6 on 2023-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0005_remove_pc_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='brand',
            field=models.CharField(default='brand name', max_length=50),
        ),
    ]
