# Generated by Django 4.2.6 on 2023-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0006_pc_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(default='Category'),
        ),
    ]
