# Generated by Django 4.2.6 on 2023-10-10 07:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0007_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='buy_link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), default=[None, None, None], size=3),
        ),
    ]
