# Generated by Django 4.2.6 on 2023-10-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0008_alter_article_buy_link'),
    ]

    operations = [
    ]
