# Generated by Django 4.2.6 on 2023-10-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0010_auto_20231010_1253'),
    ]

    operations = [
    ]
