# Generated by Django 4.2.6 on 2023-10-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0011_auto_20231010_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='buy_link',
            new_name='buy_links',
        ),
    ]
