# Generated by Django 4.2.6 on 2023-10-10 07:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0013_remove_article_buy_links_article_buy_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='buy_link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), default=list, size=3),
        ),
    ]
